export default {
  Logo: require('../assets/Images/batteryLogo.png'),
  suffix: require('../assets/Images/suffix.png'),
  HeaderPic: require('../assets/Images/HeaderPic.png'),
  location: require('../assets/Images/location.png'),
  Icon: require('../assets/Images/Icon.png'),
  back: require('../assets/Images/back.png'),
  GreenCircle: require('../assets/Images/GreenCircle.png'),
  error: require('../assets/Images/error.png'),
  fingerprint: require('../assets/Images/fingerprint.png'),
  close: require('../assets/Images/close.png'),
  batteryAnimation: require('../assets/Images/batteryAnimation.png'),
  charging: require('../assets/Images/charging.png'),
  heart: require('../assets/Images/heart.png'),
  calender: require('../assets/Images/calender.png'),
  refreshIcon: require('../assets/Images/refreshIcon.png'),
  redBorderRight: require('../assets/Images/redBorderRight.png'),
  online: require('../assets/Images/online.png'),
  offline: require('../assets/Images/offline.png'),
  current: require('../assets/Images/current.png'),
  electric: require('../assets/Images/electric.png'),
};
